version: '3.9'
services:
  app:
    image: automaticbytes/demo-app
    ports:
      - '3100:3100'
    platform: linux/arm64/v8
    networks:
      - playwright-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    network_mode: 'host'
    command: ['/bin/sh', '-c', 'npx playwright test']

networks:
  playwright-network:
    driver: bridge
