version: '3.9'
services:
  app:
    image: automaticbytes/demo-app
    ports:
      - '3100:3100'
    platform: linux/amd64
    networks:
      - playwright-network

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    network_mode: 'host'
    command: ['npx', 'playwright', 'test']

networks:
  playwright-network:
    driver: bridge
