name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - refactor
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up QEMU for cross-platform builds
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker
        run: |
          docker-compose build
          docker-compose up
          docker-compose logs -f tests || exit 1
      - name: Run Playwright
        run: npx playwright test

      - name: Debug Containers
        run: |
          docker-compose logs app
          docker-compose logs tests
          docker ps -a
          docker inspect tests --format='{{.State.ExitCode}}'
