name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - refactor
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker-compose up -d
