name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - refactor
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up QEMU for cross-platform builds
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker
        run: |
          docker-compose build
          docker-compose up
          docker-compose logs -f tests || exit 1

      - name: Copy Playwright Report
        run: docker cp $(docker-compose ps -q tests):/challenge_celara/playwright-report ./playwright-report

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./playwright-report
